[project]
name = "cai1-c1"
version = "0.1.0"
description = "File integrity verification in unsafe cloud environments"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=41.0.0",
]
