[project]
name = "cai1-c3"
version = "0.1.0"
description = "Privacy-preserving identification of persons of interest in airline passenger lists"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openmined-psi>=1.0.0",
]
